### ISSUE TITLE
[RFE] Handle VolumeAttachments explicitly to speed up failover

### ISSUE THREAD

**Issue by dyasny** [medik8s/poison-pill#103]
Based on the discussion at https://groups.google.com/g/medik8s/c/_esi9rj9mTU/m/_aGvInpSAgAJ

When a node suddenly dies, the pods using RWO volumes on it cannot be rescheduled, because of the multi-attach error. The VolumeAttachment object effectively locks the pod to the node and until it is removed, the volume cannot be rescheduled. This generally makes sense when the RWO volumes are local, but much less so for network-attached RWO volumes.

In any case, the flow currently is for the SBA mechanism to run it's course, removing the node from the cluster, which in turn eventually removes volumeattachments (or not, depending on settings and random gods of k8s API interconnections). This bring the potential downtime of a pod from a possible few seconds, to at least 5 minutes and more (the rescheduling pod retries at an exponentially growing retry timeouts as the reconciliation loop is set). 

This RFE is about deleting the VolumeAttachments belonging to the removed node explicitly to avoid the huge delays and shorten the downtime of a workload.

**Comment by n1r1** [comment]
Thanks for bringing this up @dyasny 
We will explore `volumeattachements` and `pods` direct deletion in the near future as an alternative for `node` deletion

**Comment by n1r1** [comment]
closing this as it was implemented in https://github.com/medik8s/poison-pill/pull/110
